_wandb:
    value:
        cli_version: 0.22.2
        e:
            sfvvtmrdbrrb6ob99rqlbnnwpqpaedu2:
                codePath: new_sae_code/sae_adapter/train_sae_adapter.py
                codePathLocal: train_sae_adapter.py
                cpu_count: 12
                cpu_count_logical: 24
                cudaVersion: "12.7"
                disk:
                    /:
                        total: "982820896768"
                        used: "664377348096"
                email: diyasreedhar@college.harvard.edu
                executable: /home/diya/miniforge3/bin/python
                git:
                    commit: bc707f70d226d8c3549a377036967da882f40908
                    remote: https://github.com/ds9-code/Mech-Interp.git
                gpu: NVIDIA GeForce RTX 3090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-02207e9a-fce8-1b9d-f6fc-5030ebc3903f
                host: TEJAS
                memory:
                    total: "67359764480"
                os: Linux-6.8.0-52-generic-x86_64-with-glibc2.35
                program: /media/data/divyanshu/diya/mechinterp/new_sae_code/sae_adapter/train_sae_adapter.py
                python: CPython 3.12.11
                root: /media/data/divyanshu/diya/mechinterp/new_sae_code/sae_adapter
                startedAt: "2026-02-24T06:03:53.202160Z"
                writerId: sfvvtmrdbrrb6ob99rqlbnnwpqpaedu2
        m: []
        python_version: 3.12.11
        t:
            "1":
                - 1
                - 5
                - 9
                - 11
                - 41
                - 48
                - 49
                - 53
                - 103
            "2":
                - 1
                - 5
                - 9
                - 11
                - 41
                - 48
                - 49
                - 53
                - 103
            "3":
                - 13
            "4": 3.12.11
            "5": 0.22.2
            "6": 4.57.1
            "12": 0.22.2
            "13": linux-x86_64
backbone:
    value:
        checkpoint: /media/data/divyanshu/sophont/checkpoints/brainiac_traincsv_simclr_norm_vit_cls_vitb_tejas_lr0005_best-model-epoch=11-train_loss=0.00.ckpt
        hidden_size: 768
        img_size:
            - 96
            - 96
            - 96
        in_channels: 1
        mlp_dim: 3072
        num_heads: 12
        num_layers: 12
        patch_size:
            - 16
            - 16
            - 16
data:
    value:
        batch_size: 64
        dataset_type: brainage
        embedding_csv: /media/data/divyanshu/diya/mechinterp/sae_training_new_sae/brainage_train_simclr_embeddings.csv
        embedding_npy: ""
        num_workers: 4
        size:
            - 96
            - 96
            - 96
        use_embeddings: true
logger:
    value:
        project: brainiac_sae
        run_name: sae_new_brainage
        save_dir: /media/data/divyanshu/diya/mechinterp/new_sae_checkpoints_brainage
        save_name: sae_new_brainage-{epoch:02d}-{train_loss:.4f}
model:
    value:
        adapter_type: mlp_grounded
        beta_wz: 0
        l1_weight: 3e-05
        lambda_anchor: 1
        lambda_sim: 0.01
        latent_dim: 49152
        leaky_relu_slope: 0.01
        mlp_activation: leaky_relu
        mlp_hidden_dim: 6144
        mlp_init_scale: 1
        sparsity_type: topk
        topk: 64
optim:
    value:
        lr: 0.0003
        weight_decay: 0.0001
trainer:
    value:
        devices:
            - 0
        max_epochs: 50
        precision: 16-mixed
